### ISSUE TITLE
BSM dark neutrino cross section

### ISSUE THREAD

**Issue by pmachado85** [AchillesGen/Achilles#19]
- [x] Check why QE xsec is high
- [x] Chekc if Helm FF agrees with analytic expression (unit test)

**Comment by jxi24** [comment]
Additional checks
- [ ] Figure out why there are so many channels

**Comment by jxi24** [comment]
I found the issue with the channels. There are a ton of duplicate channels that are being constructed now. It shouldn't effect the overall cross section, just slow down the calculation. I will work on removing the duplicates. I just need to determine the optimal approach to do so.

**Comment by jxi24** [comment]
These issues have been resolved.
